name: Build and Deploy to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-22

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Step 2: Set up JDK 17 for building the JAR file
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
